### PR TITLE
Adds Public Shaming for Delinquent Code Reviews

### PR DESCRIPTION
**Pull request by rringler**
Adds public shaming (to the #engineering chat room) for delinquent code
reviews.

### CODE REVIEW

**Comment by hjdivad** [comment]
What.

Why are we doing this?  This is not going to foster a good culture.

**Comment by sophylee** [comment]
The fundamental challenge is that developers are simultaneously being asked to ship code fast (by mobile), make sure all code is reviewed (from me) and having to wait sometimes 1+ days for code reviews to come back (from other devs). @rringler I agree we should have a shorter turnaround time on code review though agree with David that these comments might trigger resentment from the reviewer. Doesn't bot already remind a reviewer privately when they have an outstanding CR?

**Comment by rringler** [comment]
I've reverted this changes, as public shaming is probably not the right route to go here (even by an impartial bot.)

> Doesn't bot already remind a reviewer privately when they have an outstanding CR?

The bot will ping anyone with a CR requested more than three hours ago, but I think sensitivity to the bot reminders varies.

**Comment by sophylee** [comment]
@rringler can you please bring up this issue in retro?

**Pull request merged**
